CREATE TABLE IF NOT EXISTS Customers (
    ROLL_NO TEXT PRIMARY KEY,
    NAME TEXT NOT NULL,
    ADDRESS TEXT,
    GRADE INTEGER,
    AGE INTEGER
);

INSERT INTO Customers (ROLL_NO, NAME, ADDRESS, GRADE, AGE) VALUES 
    ('1', 'RAM', 'NEW YORK', 101, 18),
    ('2', 'RAMESH', 'LOS ANGELES', 99, 18),
    ('3', 'SUJIT', 'BOSTON', 80, 20),
    ('4', 'SURESH', 'NEW YORK', 70, 18),
    ('5', 'AMAN', 'OHIO', 160, 20),
    ('6', 'HARSH', 'ATLANTA', 120, 18);

SELECT * FROM Customers;

SELECT * FROM Customers WHERE ADDRESS = 'NEW YORK' OR GRADE > 100;

SELECT * FROM Customers WHERE ADDRESS = 'NEW YORK' AND GRADE > 100;
